#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Nov 10, 2018 05:23:11 PM JST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import rename_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    rename_support.set_Tk_var()
    top = Toplevel1 (root)
    rename_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    rename_support.set_Tk_var()
    top = Toplevel1 (w)
    rename_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

#主画面的类
class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("509x261+804+308")
        top.title("批量命名替换0.1")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.TFrame1 = ttk.Frame(top)
        self.TFrame1.place(relx=0.059, rely=0.077, relheight=0.67
                , relwidth=0.894)
        self.TFrame1.configure(relief='groove')
        self.TFrame1.configure(borderwidth="2")
        self.TFrame1.configure(relief='groove')
        self.TFrame1.configure(width=455)

        self.Button2 = tk.Button(self.TFrame1)
        self.Button2.place(relx=0.681, rely=0.114, height=28, width=89)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(command=rename_support.selectPath)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''选择目录''')

        self.Entry1 = tk.Entry(self.TFrame1)
        self.Entry1.place(relx=0.044, rely=0.114,height=27, relwidth=0.602)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")
        self.Entry1.configure(textvariable=rename_support.lujing) #文本框的变量

        self.Entry2 = tk.Entry(self.TFrame1)
        self.Entry2.place(relx=0.066, rely=0.4, relheight=0.183, relwidth=0.273)
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="TkTextFont")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(foreground="black")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")
        self.Entry2.configure(width=124)
        self.Entry2.configure(textvariable=rename_support.old_char)  # 文本框的变量

        self.Entry3 = tk.Entry(self.TFrame1)
        self.Entry3.place(relx=0.066, rely=0.686, relheight=0.183
                , relwidth=0.273)
        self.Entry3.configure(background="white")
        self.Entry3.configure(font="TkTextFont")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(foreground="black")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")
        self.Entry3.configure(textvariable=rename_support.new_char)  # 文本框的变量


        # self.Text1_2 = tk.Text(self.TFrame1)
        # self.Text1_2.place(relx=0.066, rely=0.686, relheight=0.183
        #         , relwidth=0.273)
        # self.Text1_2.configure(background="white")
        # self.Text1_2.configure(font="TkTextFont")
        # self.Text1_2.configure(foreground="black")
        # self.Text1_2.configure(highlightbackground="#d9d9d9")
        # self.Text1_2.configure(highlightcolor="black")
        # self.Text1_2.configure(insertbackground="black")
        # self.Text1_2.configure(selectbackground="#c4c4c4")
        # self.Text1_2.configure(selectforeground="black")
        # self.Text1_2.configure(width=124)
        # self.Text1_2.configure(wrap='word')

        self.TLabel1 = ttk.Label(self.TFrame1)
        self.TLabel1.place(relx=0.396, rely=0.457, height=21, width=139)
        self.TLabel1.configure(background="#d9d9d9")
        self.TLabel1.configure(foreground="#000000")
        self.TLabel1.configure(font="TkDefaultFont")
        self.TLabel1.configure(relief='flat')
        self.TLabel1.configure(text='''输入要替换的字段''')

        self.TLabel2 = ttk.Label(self.TFrame1)
        self.TLabel2.place(relx=0.396, rely=0.686, height=21, width=64)
        self.TLabel2.configure(background="#d9d9d9")
        self.TLabel2.configure(foreground="#000000")
        self.TLabel2.configure(font="TkDefaultFont")
        self.TLabel2.configure(relief='flat')
        self.TLabel2.configure(text='''输入新字段''')

        self.TButton2 = ttk.Button(self.TFrame1)
        self.TButton2.place(relx=0.659, rely=0.343, height=87, width=117)
        self.TButton2.configure(command=rename_support.do_rename)
        self.TButton2.configure(takefocus="")
        self.TButton2.configure(text='''执行替换''')

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.786, rely=0.766, height=28, width=59)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=rename_support.cancle)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''取消''')

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.766, rely=0.881, height=23, width=84)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Made by YZK''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.059, rely=0.805, height=23, width=327)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''www.do1024.com''')
        self.Label2.configure(width=327)

if __name__ == '__main__':
    vp_start_gui()





